"""Dawnlist entry point.

Two ways in, and they share everything below the surface:

    python -m app.main                 # the app
    python -m app.main --run-once      # the morning run, headless
    python -m app.main --board         # open on the board
    python -m app.main --audit         # print the board audit and exit

The headless form exists so a scheduled run and a hand-run produce identical
state — a scheduler that drives a different code path is a second system that
drifts from the first.
"""
from __future__ import annotations

import argparse
import sys
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

from app.core import db
from app.core.pipeline import (Gate, permanent_reject_gate, persist,
                               posted_within_gate, run_morning)
from app.core.rules import RuleTable
from app.feed.base import SearchQuery
from app.i18n import set_locale

DEFAULT_POSTED_WITHIN_DAYS = 45


def _force_utf8_console() -> None:
    """The Windows console is cp1252 and job titles are not.

    Measured in P0: a run died on the first en-dash AFTER the credits had
    already been spent. `--run-once` prints titles, screen reasons and verdicts,
    so this applies to BOTH streams — the first version of this file fixed only
    stdout and an em-dash on stderr still came out as a replacement character.
    """
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            try:
                stream.reconfigure(encoding="utf-8", errors="replace")
            except Exception:  # noqa: BLE001 - never block startup on this
                pass


_force_utf8_console()


class NotConfigured(RuntimeError):
    """Raised when a run is attempted before onboarding has produced a brief.

    Deliberately loud. The calibration gate is the transfer-of-judgement step
    that made the original system work, and a run against an empty brief would
    produce a plausible-looking shortlist built on nothing.
    """


def load_settings(conn) -> dict[str, str]:
    return {r["key"]: r["value"] for r in conn.execute("SELECT key, value FROM settings")}


def load_document(conn, kind: str) -> str:
    """The latest version of the fit brief or factsheet."""
    row = conn.execute(
        "SELECT body FROM documents WHERE kind=? ORDER BY version DESC LIMIT 1",
        (kind,)).fetchone()
    return row["body"] if row else ""


def load_queries(conn) -> list[SearchQuery]:
    import json
    out: list[SearchQuery] = []
    for row in conn.execute("SELECT * FROM queries WHERE enabled=1 ORDER BY id"):
        params = json.loads(row["params_json"])
        since = None
        if row["last_discovered_at"]:
            try:
                since = datetime.fromisoformat(row["last_discovered_at"])
            except ValueError:
                since = None
        out.append(SearchQuery(
            label=row["label"],
            titles=params.get("titles", []),
            countries=params.get("countries", []),
            companies=params.get("companies", []),
            posted_within_days=params.get("posted_within_days",
                                          DEFAULT_POSTED_WITHIN_DAYS),
            discovered_since=since,
            max_results=params.get("max_results", 500),
        ))
    return out


def load_rules(conn) -> RuleTable:
    import json

    from app.core.rules import KillFamily, KillFamilyError

    table = RuleTable()
    for row in conn.execute("SELECT field, term FROM rule_terms"):
        getattr(table, row["field"]).append(row["term"])

    for row in conn.execute("SELECT * FROM kill_families"):
        try:
            table.kill_families.append(KillFamily(
                name=row["name"],
                employers=tuple(json.loads(row["employers_json"])),
                kill_titles=tuple(json.loads(row["kill_json"])),
                saves_titles=tuple(json.loads(row["saves_json"])),
                precedents=tuple(tuple(p) for p in
                                 json.loads(row["precedents_json"])),
                adopted=bool(row["adopted"]),
            ))
        except KillFamilyError as exc:
            # A stored family that no longer satisfies the rules is skipped
            # LOUDLY rather than silently dropped or silently applied.
            print(f"warning: kill family {row['name']!r} is invalid and was "
                  f"not loaded: {exc}", file=sys.stderr)

    # Tier 2 is DERIVED, never typed in. `known_employers` is defined as
    # "employers the user has actually pursued", and the pursue decisions are
    # already recorded — so the rule earns itself from evidence the user
    # generated by working the shortlist, which is what "every entry is
    # earned" was always supposed to mean. Deriving it also means it cannot
    # drift: an employer stops being known when the decision is revised.
    for row in conn.execute(
            "SELECT DISTINCT j.company FROM decisions d "
            "JOIN jobs j ON j.id = d.job_id "
            "WHERE d.kind = 'pursue' AND j.company <> ''"):
        if row["company"] not in table.known_employers:
            table.known_employers.append(row["company"])
    return table


RULE_FIELDS = ("unsupported_titles", "strong_terms", "contextual_terms")


def save_rule_term(conn, field: str, term: str) -> None:
    """Add one screening term.

    `known_employers` is deliberately not writable here: it is derived from
    pursue decisions in `load_rules`, and a hand-typed copy would drift from
    the decisions the moment one was revised.

    A tier-1 term is checked against the user's own pursue history before it
    is admitted. spec 5.3: a kill term that would have removed a role they
    actually chased is not a rule, it is a mistake about to repeat itself.
    """
    from app.core.rules import assert_no_conflicts

    field = field.strip()
    term = term.strip()
    if field not in RULE_FIELDS:
        raise ValueError(f"unknown rule field {field!r}; expected one of "
                         f"{', '.join(RULE_FIELDS)}")
    if not term:
        raise ValueError("a rule term cannot be empty")

    # Admission-time, and against the table the term would JOIN rather than the
    # term alone: a guard that only sees the new term cannot tell that the
    # table as a whole would now remove a role the user chased.
    proposed = load_rules(conn)
    getattr(proposed, field).append(term)
    pursued = [(r["company"], r["title"]) for r in conn.execute(
        "SELECT j.company, j.title FROM decisions d "
        "JOIN jobs j ON j.id = d.job_id WHERE d.kind = 'pursue'")]
    assert_no_conflicts(proposed, pursued)

    conn.execute(
        "INSERT INTO rule_terms(field, term, added_at) VALUES(?,?,?) "
        "ON CONFLICT DO NOTHING",
        (field, term, datetime.now(timezone.utc).isoformat(timespec="seconds")))
    conn.commit()


def forget_rule_term(conn, field: str, term: str) -> None:
    conn.execute("DELETE FROM rule_terms WHERE field=? AND term=?",
                 (field, term.strip()))
    conn.commit()


def mark_queries_run(conn, when: datetime | None = None) -> None:
    """Advance each query's delta high-water mark.

    handoff 2.1a: billing is per job RETURNED, so re-fetching yesterday's
    postings is re-buying them. This is written only after a run completes.
    """
    when = when or datetime.now(timezone.utc)
    conn.execute("UPDATE queries SET last_discovered_at=? WHERE enabled=1",
                 (when.isoformat(timespec="seconds"),))
    conn.commit()


def build_provider(conn):
    """The feed provider, from the stored settings.

    Kept behind a function so a BYO-keys user, a managed-tier user routed
    through the Worker, and a future dataset adapter all enter the same way.
    """
    import keyring

    from app.feed.theirstack import TheirStackProvider

    key = keyring.get_password("dawnlist-feed", "api-key")
    if not key:
        raise NotConfigured(
            "No feed credential found. Store one under the keyring service "
            "'dawnlist-feed', account 'api-key', or sign in to the managed tier.")
    return TheirStackProvider(key)


def build_send(conn):
    """The assessment transport, on the USER's own Anthropic key.

    Dawnlist is bring-your-own-key, and that is a DATA decision before it is a
    pricing one. Job descriptions, the fit brief and the background factsheet
    are the user's career history. Routing them through Spencer's own
    infrastructure would make him a processor of every buyer's employment
    record — with the retention, breach-notification and international-transfer
    duties that follow — in exchange for saving them one setup step.

    So the call goes straight from the user's machine to Anthropic on the
    user's key. There is no managed route to fall back to, deliberately: a
    fallback is how data starts crossing infrastructure nobody decided it
    should cross.
    """
    import anthropic

    from app.core import api_key

    client = anthropic.Anthropic(api_key=api_key.require())

    def send(request: dict):
        response = client.messages.create(**request)
        return "".join(b.text for b in response.content if b.type == "text")

    return send


def morning_run(conn, *, provider=None, send=None, today: date | None = None):
    """One morning run, with the gates the stored state implies."""
    from app.ui.adapter import rejected_keys

    from app.onboarding.calibration import is_calibrated

    brief = load_document(conn, "fit_brief")
    factsheet = load_document(conn, "factsheet")
    if not brief.strip():
        raise NotConfigured(
            "No fit brief yet. Run onboarding first — a run against an empty "
            "brief produces a plausible shortlist built on nothing.")
    if not is_calibrated(conn):
        # The gate is checked HERE, at the only door into a run, rather than in
        # the UI. A gate enforced in a screen is a gate the scheduled run walks
        # straight past.
        raise NotConfigured(
            "Calibration has not been completed. The app must show you ~10 "
            "live postings and have you correct its verdicts before it runs "
            "daily — that is the step that transfers your judgement into the "
            "brief, and without it the shortlist is a guess that looks like an "
            "answer.")

    # The entitlement gate sits HERE, next to the calibration gate, for the
    # same reason: a gate enforced in a screen is one the scheduled run walks
    # straight past. Only the run is gated — onboarding, the board and every
    # screen stay open whether or not anyone has paid.
    from app.core.entitlement import require as require_entitlement
    require_entitlement(conn)

    queries = load_queries(conn)
    if not queries:
        raise NotConfigured("No saved queries. Add at least one before running.")

    seen = {(r["provider"], r["provider_job_id"])
            for r in conn.execute("SELECT provider, provider_job_id FROM seen_jobs")}

    gates: list[Gate] = [
        permanent_reject_gate(rejected_keys(conn)),
        posted_within_gate(DEFAULT_POSTED_WITHIN_DAYS, today=today),
    ]

    outcome = run_morning(
        conn, provider or build_provider(conn), queries, load_rules(conn),
        fit_brief=brief, factsheet=factsheet,
        send=send or build_send(conn), gates=gates, already_seen=seen,
    )
    persist(conn, outcome)
    if not outcome.fetch_errors:
        # Only advance the delta mark on a clean fetch. Advancing it after a
        # failure would skip the window the failed run never actually read.
        mark_queries_run(conn)
    return outcome


def print_funnel(outcome) -> None:
    """The whole funnel, never one number without what it excludes."""
    counts = outcome.funnel()
    width = max(len(k) for k in counts)
    for key, value in counts.items():
        print(f"  {key.replace('_', ' '):<{width}}  {value}")
    if outcome.fetch_errors:
        print("\n  FETCH PROBLEMS — this run is incomplete:")
        for err in outcome.fetch_errors:
            print(f"    - {err}")
    if outcome.unscored_queries:
        print(f"\n  no yield rate computed for: "
              f"{', '.join(outcome.unscored_queries)} (fetch failed)")
    loose = outcome.loose_queries()
    if loose:
        print(f"\n  below 10% yield, rewrite rather than widen: {', '.join(loose)}")



def drafts_dir() -> Path:
    """Where `.eml` files land. Beside the database, never a synced folder —
    a draft is unsent correspondence and has no business in OneDrive."""
    return db.default_db_path().parent / "drafts"


def outreach_run(conn, *, send=None, today: date | None = None,
                 folder: Path | None = None):
    """Draft everything due. Writes files; sends nothing, ever.

    The board decides what is due and the cadence decides when — this only
    turns that list into files the user opens and sends themselves. There is
    deliberately no transport here and no credential that could grow one.
    """
    from app.outreach.run import due_today, prepare_drafts
    from app.outreach.voice import build_profile

    factsheet = load_document(conn, "factsheet")
    if not factsheet.strip():
        raise NotConfigured(
            "No background factsheet yet. Run onboarding first — every factual "
            "claim in a draft has to come from it, so without one a draft is "
            "either empty or invented.")

    from app.core.entitlement import require as require_entitlement
    require_entitlement(conn)

    folder = folder or drafts_dir()
    folder.mkdir(parents=True, exist_ok=True)

    items = due_today(conn, today=today)
    settings = load_settings(conn)
    return prepare_drafts(
        conn, items, folder=folder, factsheet=factsheet,
        voice=load_voice(conn), send=send or build_send(conn),
        locale=settings.get("locale", "en"), today=today)


#: Sent mail the user has supplied, for measuring how they write. Files rather
#: than a table, and deliberately: `documents` is constrained to the fit brief
#: and the factsheet, and widening that CHECK to admit a mail archive would put
#: correspondence in the same store as the two documents that govern truth.
#: Dawnlist never reads a mailbox — these are files a person put here.
VOICE_DIRNAME = "voice"


def voice_dir() -> Path:
    return db.default_db_path().parent / VOICE_DIRNAME


def load_voice(conn, folder: Path | None = None):
    """The user's own tone of voice, measured from mail they supplied.

    Falls back to a neutral profile rather than failing: someone who has added
    no sent mail should still get drafts, in nobody's particular voice, rather
    than no drafts at all. Style only — never content. What a past message
    SAID is not evidence for anything a new one may claim; only the factsheet
    is.
    """
    from app.outreach.voice import build_profile, profile_from_files

    settings = load_settings(conn)
    folder = folder or Path(settings.get("voice_dir") or voice_dir())
    if not folder.is_dir():
        return build_profile([])

    paths = sorted(p for p in folder.iterdir()
                   if p.suffix.lower() in {".eml", ".txt", ".md"})
    if not paths:
        return build_profile([])
    return profile_from_files(paths, locale=settings.get("locale", "en"))


def print_outreach(report) -> None:
    counts = report.counts
    width = max(len(k) for k in counts)
    for key, value in counts.items():
        print(f"  {key.replace('_', ' '):<{width}}  {value}")
    for item in report.blocked:
        print(f"    blocked: {item.opportunity.company} — {item.blocked}")
    for draft in report.drafts.blocked:
        print(f"    needs evidence: {draft.to_name} — "
              f"{', '.join(draft.placeholders)}")
    if report.drafts.drafts:
        print(f"\n  written to {drafts_dir()}")
    print("\n  Nothing was sent. Open each file and send it yourself.")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="dawnlist")
    parser.add_argument("--run-once", action="store_true",
                        help="run the morning sweep headlessly and exit")
    parser.add_argument("--board", action="store_true",
                        help="open on the board rather than the shortlist")
    parser.add_argument("--audit", action="store_true",
                        help="print the board audit and exit")
    parser.add_argument("--doctor", action="store_true",
                        help="print environment diagnostics and exit")
    parser.add_argument("--draft", action="store_true",
                        help="draft every outreach that is due; sends nothing")
    parser.add_argument("--settings", action="store_true",
                        help="open settings alone, without the rest of the app")
    parser.add_argument("--onboard", action="store_true",
                        help="open the setup flow, even if already calibrated")
    parser.add_argument("--db", type=Path, default=None,
                        help="database path (defaults to the app data dir)")
    parser.add_argument("--locale", default=None, help="UI locale, e.g. fr")
    args = parser.parse_args(argv)

    conn = db.connect(args.db)
    db.migrate(conn)

    settings = load_settings(conn)
    set_locale(args.locale or settings.get("locale", "en"))

    if args.doctor:
        return _doctor(conn)

    if args.audit:
        from app.core.board_repo import audit_board
        findings = audit_board(conn)
        print(f"{len(findings['scanned'])} opportunities checked")
        for key in ("bounce_corrections", "parity_defects",
                    "duplicate_open_children"):
            for item in findings[key]:
                print(f"  {key}: {item}")
        return 0

    if args.run_once:
        from app.core.api_key import KeyProblem
        from app.core.entitlement import NotEntitled

        try:
            outcome = morning_run(conn)
        except KeyProblem as exc:
            # Exit 4: distinct from "not set up" (2) and "not paid" (3),
            # because the fix is different again.
            print(f"no api key: {exc}", file=sys.stderr)
            return 4
        except NotEntitled as exc:
            # Exit 3, distinct from 2: "not paid" and "not set up" want
            # different responses from whatever is running this.
            print(f"not entitled: {exc}", file=sys.stderr)
            return 3
        except NotConfigured as exc:
            print(f"not configured: {exc}", file=sys.stderr)
            return 2
        print_funnel(outcome)
        # An incomplete run exits non-zero so a scheduler notices. A run that
        # fetched nothing because the endpoint failed must never look like a
        # quiet morning.
        return 0 if outcome.complete else 1

    if args.draft:
        from app.core.api_key import KeyProblem
        from app.core.entitlement import NotEntitled

        try:
            report = outreach_run(conn)
        except KeyProblem as exc:
            print(f"no api key: {exc}", file=sys.stderr)
            return 4
        except NotEntitled as exc:
            print(f"not entitled: {exc}", file=sys.stderr)
            return 3
        except NotConfigured as exc:
            print(f"not configured: {exc}", file=sys.stderr)
            return 2
        print_outreach(report)
        return 0

    if args.settings:
        # Reachable without a working key or a passed gate on purpose: the
        # state this is most needed in is the one where nothing else starts.
        from PySide6.QtWidgets import QApplication
        app = QApplication.instance() or QApplication(sys.argv)
        # Bound, and it looks unused: this local is the ONLY reference to the
        # window, and letting it go collects the widget before exec() runs.
        window = open_settings(conn=conn)  # noqa: F841
        assert window is not None
        return app.exec()

    if args.onboard:
        from PySide6.QtWidgets import QApplication
        app = QApplication.instance() or QApplication(sys.argv)
        return _launch_onboarding(app, conn)

    return _launch_ui(conn, open_board=args.board)


def _doctor(conn) -> int:
    """Environment diagnostics.

    Exists because a frozen build fails differently from a source run: a
    resource read by path at runtime can simply be absent from the bundle, and
    the app degrades quietly rather than crashing. This prints what actually
    resolved, so "it is not translating" is one command to diagnose rather than
    a support thread.
    """
    from app.i18n import LOCALE_CODES, LOCALES_DIR, coverage
    from app.onboarding.calibration import is_calibrated

    from app.core.build_variant import variant

    frozen = getattr(sys, "frozen", False)
    print(f"dawnlist      : {'frozen' if frozen else 'source'}")
    # A Store package that is silently the direct-download build is exactly
    # what the flags exist to prevent, so the variant is reported.
    v = variant()
    print(f"build variant : {v}")
    if v in ("none", "ambiguous"):
        print(f"  WARNING: variant is {v} — this build carries no usable "
              f"variant flag.", file=sys.stderr)
    print(f"database      : {conn.execute('PRAGMA database_list').fetchone()[2]}")
    print(f"locales dir   : {LOCALES_DIR}")
    print(f"locales exist : {LOCALES_DIR.exists()}")

    cov = coverage()
    shipped = sorted(c for c in LOCALE_CODES if cov[c] > 0)
    print(f"catalogues    : {len(shipped)} of {len(LOCALE_CODES)} "
          f"({', '.join(shipped) if shipped else 'none'})")
    if not shipped:
        # The exact failure the spec's `datas` entry exists to prevent.
        print("  WARNING: no catalogues resolved. Every locale will fall back "
              "to English silently. Check the spec collects "
              "app/resources/locales.", file=sys.stderr)

    # Reported because a missing extractor in a frozen build shows up to the
    # user as "no text could be read", which points at their CV rather than at
    # the bundle.
    for module, what in (("pypdf", "PDF"), ("docx", "Word")):
        try:
            __import__(module)
            print(f"{what + ' reading':<14}: available")
        except ImportError:
            print(f"{what + ' reading':<14}: MISSING ({module} not bundled)",
                  file=sys.stderr)

    from app.core.entitlement import check as check_entitlement

    from app.core import api_key as user_key

    from app.core import api_key as user_key

    stored = user_key.get()
    print(f"anthropic key : {'present' if stored else 'MISSING'}")
    if not stored:
        print("  Dawnlist uses your own Anthropic key. Add one in Settings.",
              file=sys.stderr)

    ent = check_entitlement(conn)
    state = ent.source if ent.entitled else "NOT ENTITLED"
    print(f"entitlement   : {state}")
    if not ent.entitled:
        print(f"  {ent.reason}", file=sys.stderr)
    elif ent.source in ("trial", "grace"):
        print(f"  {ent.reason}")

    print(f"calibrated    : {is_calibrated(conn)}")
    print(f"queries       : {len(load_queries(conn))}")
    print(f"fit brief     : {'yes' if load_document(conn, 'fit_brief') else 'no'}")
    return 0 if shipped else 1


def _launch_onboarding(app, conn) -> int:
    """The setup flow. Opened automatically when the gate has not been passed.

    Routing here rather than to an empty shortlist is the honest thing to show
    a new user: the shortlist would be empty anyway, and an empty screen with
    no explanation reads as a broken app rather than an unfinished setup.
    """
    from app.onboarding.calibration import complete_calibration
    from app.onboarding.extract import extract_corpus
    from app.ui.onboarding import OnboardingWizard

    def extract(paths):
        result = extract_corpus(list(paths))
        return [d.name for d in result.corpus.documents], result.warnings

    def sample():
        # The calibration sample comes from a real feed pull. Until a feed
        # credential is configured there is nothing honest to show, so the
        # wizard says so rather than inventing postings to practise on.
        from app.onboarding.calibration import CalibrationItem
        return [CalibrationItem(
            job_key="setup", title="No live postings yet",
            company="", description="",
            app_verdict="possible",
            app_reason=("a feed credential is needed before Dawnlist can "
                        "fetch the postings you calibrate against"))]

    def drafter(paths):
        """CVs in, factsheet and brief out, on the user's own key."""
        import json

        from app.core import api_key
        from app.onboarding.extract import extract_corpus
        from app.onboarding.interview import (build_brief_request,
                                              build_factsheet_request,
                                              open_questions, render_factsheet,
                                              text_of)

        import anthropic
        client = anthropic.Anthropic(api_key=api_key.require())

        def call(request):
            # Streamed, not `create`. The SDK REFUSES a non-streaming request
            # whose max_tokens could exceed a ten-minute response — it raises
            # ValueError before anything is sent, so the app would fail on the
            # first real corpus with a message about streaming rather than
            # about CVs. The factsheet needs that budget (see
            # FACTSHEET_MAX_TOKENS), so the transport has to stream.
            with client.messages.stream(**request) as stream:
                return text_of(stream.get_final_message())

        corpus = extract_corpus(list(paths)).corpus
        if not corpus.usable:
            raise RuntimeError("no readable CV text was found")

        raw = call(build_factsheet_request(corpus))
        data = json.loads(raw)
        factsheet = render_factsheet(data)
        brief = call(build_brief_request(corpus, ""))
        return factsheet, brief, open_questions(data)

    wizard = OnboardingWizard(extract=extract, sample=sample, drafter=drafter)

    def save_documents(factsheet, brief):
        # Saved when the user leaves the interview, not when the model returns.
        # What is stored is what they CORRECTED, which is the whole point of
        # showing them a draft rather than a result.
        from app.onboarding.interview import save_document
        if factsheet.strip():
            save_document(conn, "factsheet", factsheet)
        if brief.strip():
            save_document(conn, "fit_brief", brief)

    def finished(result):
        brief = load_document(conn, "fit_brief") or "# Fit brief"
        complete_calibration(conn, brief, result)
        wizard.close()

    wizard.documents_ready.connect(save_documents)
    wizard.completed.connect(finished)
    wizard.resize(900, 780)
    wizard.show()
    return app.exec()



def _stored_funnel(conn, run_id) -> dict[str, int]:
    """The funnel bar for a run that is no longer in memory.

    Returned empty when there is no run: the bar states what a number excludes,
    and inventing zeroes would say a run happened and found nothing.
    """
    if run_id is None:
        return {}
    row = conn.execute(
        "SELECT swept, deduped, gated, screened_likely, screened_out, "
        "assessed, left_unread FROM runs WHERE id=?", (run_id,)).fetchone()
    if row is None:
        return {}
    # `gated` on disk, `gated_out` in memory. The funnel bar reads the
    # in-memory names, so the rename happens here rather than in the window —
    # a bar that silently omits a stage looks like a run that skipped it.
    counts = {k: row[k] or 0 for k in row.keys()}
    counts["gated_out"] = counts.pop("gated")
    return counts


def open_settings(parent=None, conn=None):
    """The settings window, wired to the real keyring.

    Held on the parent rather than returned into a local: a QWidget with no
    reference is garbage-collected the moment the function returns, and the
    window vanishes as fast as it appeared.
    """
    from app.ui.settings import RulesPanel, SettingsWindow

    # The key and licence panels already default to the real keyring and the
    # real redeemer; the injection points exist so the tests can spend nothing.
    # The rules panel cannot default, because the rules are per-user and live
    # in the database — so it is offered only when there is one.
    rules = None
    if conn is not None:
        rules = RulesPanel(
            loader=lambda: load_rules(conn),
            saver=lambda field, term: save_rule_term(conn, field, term),
            forgetter=lambda field, term: forget_rule_term(conn, field, term))

    window = SettingsWindow(rules=rules)
    if parent is not None:
        parent._settings_window = window
    window.show()
    return window


def _launch_ui(conn, *, open_board: bool) -> int:
    from PySide6.QtWidgets import QApplication

    from app.onboarding.calibration import is_calibrated
    from app.ui.adapter import connect_window, latest_run_id, rows_from_db
    from app.ui.board import BoardWindow
    from app.ui.board_adapter import board_rows, connect_board
    from app.ui.review import ReviewWindow

    app = QApplication.instance() or QApplication(sys.argv)

    if not is_calibrated(conn) and not open_board:
        return _launch_onboarding(app, conn)

    if open_board:
        window = BoardWindow()
        connect_board(window, conn)
        rows, findings = board_rows(conn)
        window.load(rows, findings)
    else:
        window = ReviewWindow()
        window.settings_requested.connect(lambda: open_settings(window, conn))
        connect_window(window, conn)
        # The last run's shortlist, read back from the database rather than
        # held from a run this process did. Opening the app the morning after
        # is the normal case, and this window used to open empty in it — every
        # posting the run assessed was on disk and nothing put it on screen.
        window.load(rows_from_db(conn), _stored_funnel(conn, latest_run_id(conn)))

    window.show()
    return app.exec()


if __name__ == "__main__":
    raise SystemExit(main())
