/**
 * The licence email's wording, in every language the application ships.
 *
 * GENERATED by tools/gen_email_strings.py — edit the English there and
 * re-run. Hand edits here are overwritten by the next run.
 *
 * A language with no entry falls back to English, so a partial run
 * degrades to the previous behaviour rather than to blank paragraphs.
 */
export const EMAIL_STRINGS = {
  "ar": {
    "subject": "مفتاح ترخيص Dawnlist الخاص بك",
    "preheader": "الصقه في الإعدادات لتفعيل التطبيق.",
    "heading": "مفتاح ترخيص Dawnlist الخاص بك",
    "thanks": "شكرًا لاشتراكك. هذا هو المفتاح الذي يفعّل التطبيق.",
    "to_use_heading": "طريقة الاستخدام",
    "to_use_body": "افتح Dawnlist، وانتقل إلى الإعدادات، والصق المفتاح في حقل الترخيص. يعمل المفتاح على كل جهاز تملكه، وعلى إصداري Windows وmacOS كليهما.",
    "allowance": "تشمل خطتك حتى {count} إعلان وظيفي يوميًا.",
    "own_key": "ستحتاج أيضًا إلى مفتاح Anthropic API خاص بك — إذ يقرأ Dawnlist الإعلانات ويصيغ الرسائل باستخدام حسابك أنت وليس حسابنا، لذا لا تصل سيرتك الذاتية ولا مراسلاتك إلى خوادمنا مطلقًا. يرشدك التطبيق خطوة بخطوة لإضافته أثناء الإعداد.",
    "not_installed": "لم تُثبّت التطبيق بعد؟ كل ما تحتاجه موجود على",
    "reply_note": "إذا واجهت أي مشكلة، ردّ على هذه الرسالة — فهي تصل إلى شخص حقيقي.",
    "footer": "Dawnlist — أحد منتجات Spencer Fields Software."
  },
  "de": {
    "subject": "Dein Dawnlist-Lizenzschlüssel",
    "preheader": "Füge diesen unter Einstellungen ein, um die Anwendung freizuschalten.",
    "heading": "Dein Dawnlist-Lizenzschlüssel",
    "thanks": "Vielen Dank für dein Abonnement. Hier ist der Schlüssel, der die Anwendung freischaltet.",
    "to_use_heading": "So geht's",
    "to_use_body": "Öffne Dawnlist, gehe zu Einstellungen und füge den Schlüssel in das Lizenzfeld ein. Er funktioniert auf jedem Computer, den du besitzt, sowohl in der Windows- als auch in der macOS-Version.",
    "allowance": "Dein Plan umfasst bis zu {count} Stellenanzeigen pro Tag.",
    "own_key": "Außerdem benötigst du einen eigenen Anthropic-API-Schlüssel — Dawnlist liest Stellenanzeigen und verfasst Nachrichten über dein eigenes Konto und nicht über unseres, sodass dein Lebenslauf und deine Korrespondenz niemals unsere Server erreichen. Die Anwendung führt dich bei der Einrichtung durch die entsprechenden Schritte.",
    "not_installed": "Noch nicht installiert? Alles Weitere findest du unter",
    "reply_note": "Falls etwas nicht funktioniert, antworte einfach auf diese Nachricht — sie erreicht einen echten Menschen.",
    "footer": "Dawnlist — ein Produkt von Spencer Fields Software."
  },
  "en": {
    "subject": "Your Dawnlist licence key",
    "preheader": "Paste this into Settings to unlock the application.",
    "heading": "Your Dawnlist licence key",
    "thanks": "Thank you for subscribing. Here is the key that unlocks the application.",
    "to_use_heading": "To use it",
    "to_use_body": "Open Dawnlist, go to Settings, and paste the key into the licence field. It works on every computer you own, and on both the Windows and macOS editions.",
    "allowance": "Your plan covers up to {count} postings a day.",
    "own_key": "You will also need an Anthropic API key of your own — Dawnlist reads postings and drafts messages on your account rather than ours, so your CV and your correspondence never reach our servers. The application walks you through adding it during setup.",
    "not_installed": "Haven't installed it yet? Everything is at",
    "reply_note": "If anything does not work, reply to this message — it reaches a person.",
    "footer": "Dawnlist — a product of Spencer Fields Software."
  },
  "es": {
    "subject": "Tu clave de licencia de Dawnlist",
    "preheader": "Pégala en Ajustes para desbloquear la aplicación.",
    "heading": "Tu clave de licencia de Dawnlist",
    "thanks": "Gracias por suscribirte. Aquí tienes la clave que desbloquea la aplicación.",
    "to_use_heading": "Cómo usarla",
    "to_use_body": "Abre Dawnlist, ve a Ajustes y pega la clave en el campo de licencia. Funciona en todos los ordenadores que tengas, tanto en la edición de Windows como en la de macOS.",
    "allowance": "Tu plan incluye hasta {count} ofertas de empleo al día.",
    "own_key": "También necesitarás tu propia clave de API de Anthropic: Dawnlist lee las ofertas y redacta los mensajes usando tu cuenta, no la nuestra, así que tu currículum y tu correspondencia nunca llegan a nuestros servidores. La aplicación te guía para añadirla durante la configuración.",
    "not_installed": "¿Aún no la has instalado? Todo está en",
    "reply_note": "Si algo no funciona, responde a este mensaje: lo lee una persona.",
    "footer": "Dawnlist — un producto de Spencer Fields Software."
  },
  "fa": {
    "subject": "کلید مجوز Dawnlist شما",
    "preheader": "این را در بخش تنظیمات وارد کنید تا برنامه فعال شود.",
    "heading": "کلید مجوز Dawnlist شما",
    "thanks": "از اشتراک شما سپاسگزاریم. این هم کلیدی که برنامه را فعال می‌کند.",
    "to_use_heading": "روش استفاده",
    "to_use_body": "Dawnlist را باز کنید، به بخش تنظیمات بروید و کلید را در فیلد مجوز وارد کنید. این کلید روی تمام رایانه‌های شما و در نسخه‌های Windows و macOS کار می‌کند.",
    "allowance": "طرح شما تا {count} آگهی شغلی در روز را پوشش می‌دهد.",
    "own_key": "همچنین به یک کلید API از Anthropic نیاز دارید که خودتان تهیه می‌کنید — Dawnlist آگهی‌ها را می‌خواند و پیام‌ها را با حساب شما، نه حساب ما، می‌نویسد؛ به این ترتیب رزومه و مکاتبات شما هرگز به سرورهای ما نمی‌رسد. برنامه در حین راه‌اندازی مراحل افزودن آن را به شما نشان می‌دهد.",
    "not_installed": "هنوز برنامه را نصب نکرده‌اید؟ همه چیز اینجاست:",
    "reply_note": "اگر چیزی درست کار نکرد، به همین پیام پاسخ دهید — این پاسخ را یک نفر می‌خواند.",
    "footer": "Dawnlist — محصولی از Spencer Fields Software."
  },
  "fr": {
    "subject": "Votre clé de licence Dawnlist",
    "preheader": "Collez-la dans Réglages pour déverrouiller l'application.",
    "heading": "Votre clé de licence Dawnlist",
    "thanks": "Merci pour votre abonnement. Voici la clé qui déverrouille l'application.",
    "to_use_heading": "Pour l'utiliser",
    "to_use_body": "Ouvrez Dawnlist, allez dans Réglages, puis collez la clé dans le champ de licence. Elle fonctionne sur tous vos ordinateurs, aussi bien sur les versions Windows que macOS.",
    "allowance": "Votre forfait couvre jusqu'à {count} annonces par jour.",
    "own_key": "Il vous faudra également votre propre clé API Anthropic — Dawnlist lit les annonces et rédige les messages avec votre compte, et non le nôtre, si bien que votre CV et votre correspondance n'atteignent jamais nos serveurs. L'application vous guide pour l'ajouter lors de la configuration.",
    "not_installed": "Pas encore installé l'application ? Tout se trouve sur",
    "reply_note": "Si quelque chose ne fonctionne pas, répondez à ce message — il est lu par une personne.",
    "footer": "Dawnlist — un produit de Spencer Fields Software."
  },
  "hi": {
    "subject": "आपकी Dawnlist लाइसेंस कुंजी",
    "preheader": "एप्लिकेशन को अनलॉक करने के लिए इसे सेटिंग्स में पेस्ट करें।",
    "heading": "आपकी Dawnlist लाइसेंस कुंजी",
    "thanks": "सदस्यता लेने के लिए धन्यवाद। यह रही वह कुंजी जो एप्लिकेशन को अनलॉक करती है।",
    "to_use_heading": "इस्तेमाल कैसे करें",
    "to_use_body": "Dawnlist खोलें, सेटिंग्स में जाएं, और कुंजी को लाइसेंस फ़ील्ड में पेस्ट करें। यह आपके हर कंप्यूटर पर काम करती है, और Windows तथा macOS दोनों संस्करणों पर भी।",
    "allowance": "आपकी योजना प्रतिदिन {count} तक पोस्टिंग को कवर करती है।",
    "own_key": "आपको अपनी खुद की Anthropic API कुंजी भी चाहिए होगी — Dawnlist पोस्टिंग पढ़ता है और संदेश आपके खाते पर तैयार करता है, हमारे खाते पर नहीं, इसलिए आपका CV और आपका पत्राचार कभी भी हमारे सर्वर तक नहीं पहुंचता। सेटअप के दौरान एप्लिकेशन आपको इसे जोड़ने की प्रक्रिया में मार्गदर्शन करता है।",
    "not_installed": "अभी तक इंस्टॉल नहीं किया? सब कुछ यहां है:",
    "reply_note": "अगर कुछ काम न करे, तो इस संदेश का जवाब दें — यह एक व्यक्ति तक पहुंचता है।",
    "footer": "Dawnlist — Spencer Fields Software का एक उत्पाद।"
  },
  "id": {
    "subject": "Kunci lisensi Dawnlist Anda",
    "preheader": "Tempelkan ini di Pengaturan untuk membuka aplikasi.",
    "heading": "Kunci lisensi Dawnlist Anda",
    "thanks": "Terima kasih telah berlangganan. Berikut kunci untuk membuka aplikasi.",
    "to_use_heading": "Cara menggunakannya",
    "to_use_body": "Buka Dawnlist, masuk ke Pengaturan, lalu tempelkan kunci tersebut ke kolom lisensi. Kunci ini berlaku di setiap komputer yang Anda miliki, baik untuk edisi Windows maupun macOS.",
    "allowance": "Paket Anda mencakup hingga {count} lowongan per hari.",
    "own_key": "Anda juga memerlukan kunci API Anthropic milik Anda sendiri — Dawnlist membaca lowongan dan menyusun pesan menggunakan akun Anda, bukan akun kami, sehingga CV dan korespondensi Anda tidak pernah sampai ke server kami. Aplikasi akan memandu Anda menambahkannya saat pengaturan awal.",
    "not_installed": "Belum menginstalnya? Semuanya ada di",
    "reply_note": "Jika ada yang tidak berfungsi, balas pesan ini — akan dibaca langsung oleh orang kami.",
    "footer": "Dawnlist — sebuah produk dari Spencer Fields Software."
  },
  "ja": {
    "subject": "Dawnlistのライセンスキー",
    "preheader": "これを設定に貼り付けて、アプリを有効化してください。",
    "heading": "Dawnlistのライセンスキー",
    "thanks": "ご登録ありがとうございます。アプリを有効化するキーをお送りします。",
    "to_use_heading": "使い方",
    "to_use_body": "Dawnlistを開き、設定画面に進み、ライセンスキー欄にこのキーを貼り付けてください。お使いのすべてのパソコンでご利用いただけ、Windows版・macOS版のどちらでも使えます。",
    "allowance": "ご契約のプランでは、1日あたり{count}件までの求人情報に対応しています。",
    "own_key": "また、ご自身でAnthropicのAPIキーをご用意いただく必要があります。Dawnlistは弊社ではなくお客様ご自身のアカウントで求人情報の読み取りやメッセージの作成を行うため、履歴書やメッセージのやり取りが弊社のサーバーに送られることはありません。キーの追加方法はセットアップ時にアプリがご案内します。",
    "not_installed": "まだインストールがお済みでない方は、こちらから",
    "reply_note": "うまくいかない場合は、このメールにご返信ください。担当者が直接お読みします。",
    "footer": "Dawnlist — Spencer Fields Softwareの製品です。"
  },
  "ko": {
    "subject": "Dawnlist 라이선스 키",
    "preheader": "설정에 붙여넣어 애플리케이션을 활성화하세요.",
    "heading": "Dawnlist 라이선스 키",
    "thanks": "구독해 주셔서 감사합니다. 애플리케이션을 활성화하는 키를 보내드립니다.",
    "to_use_heading": "사용 방법",
    "to_use_body": "Dawnlist를 열고 설정으로 이동한 다음, 라이선스 필드에 키를 붙여넣으세요. 이 키는 소유하신 모든 컴퓨터에서, Windows와 macOS 버전 모두에서 사용할 수 있습니다.",
    "allowance": "요금제는 하루 최대 {count}건의 채용 공고를 지원합니다.",
    "own_key": "또한 본인 명의의 Anthropic API 키가 필요합니다 — Dawnlist는 저희 서버가 아닌 회원님의 계정으로 채용 공고를 읽고 메시지 초안을 작성하므로, 이력서와 대화 내용이 저희 서버로 전송되지 않습니다. 설정 과정에서 키를 추가하는 방법을 안내해 드립니다.",
    "not_installed": "아직 설치하지 않으셨나요? 모든 내용은 여기에 있습니다:",
    "reply_note": "문제가 있으시면 이 메일에 답장해 주세요 — 실제 담당자가 확인합니다.",
    "footer": "Dawnlist — Spencer Fields Software의 제품입니다."
  },
  "pt": {
    "subject": "A sua chave de licença do Dawnlist",
    "preheader": "Cole isto em Definições para desbloquear a aplicação.",
    "heading": "A sua chave de licença do Dawnlist",
    "thanks": "Obrigado pela subscrição. Aqui está a chave que desbloqueia a aplicação.",
    "to_use_heading": "Como utilizar",
    "to_use_body": "Abra o Dawnlist, aceda a Definições e cole a chave no campo de licença. Funciona em todos os computadores que possui, tanto na versão Windows como macOS.",
    "allowance": "O seu plano cobre até {count} anúncios por dia.",
    "own_key": "Também vai precisar de uma chave de API da Anthropic sua — o Dawnlist lê os anúncios e redige as mensagens na sua conta, e não na nossa, pelo que o seu currículo e a sua correspondência nunca chegam aos nossos servidores. A aplicação guia-o na configuração durante a instalação.",
    "not_installed": "Ainda não instalou? Encontra tudo em",
    "reply_note": "Se algo não funcionar, responda a esta mensagem — chega a uma pessoa real.",
    "footer": "Dawnlist — um produto da Spencer Fields Software."
  },
  "ru": {
    "subject": "Ваш лицензионный ключ Dawnlist",
    "preheader": "Вставьте его в Настройках, чтобы разблокировать приложение.",
    "heading": "Ваш лицензионный ключ Dawnlist",
    "thanks": "Спасибо за оформление подписки. Вот ключ, который разблокирует приложение.",
    "to_use_heading": "Как использовать",
    "to_use_body": "Откройте Dawnlist, перейдите в Настройки и вставьте ключ в поле лицензии. Он работает на всех ваших компьютерах, а также в версиях для Windows и macOS.",
    "allowance": "Ваш тариф позволяет обрабатывать до {count} объявлений в день.",
    "own_key": "Вам также понадобится собственный API-ключ Anthropic — Dawnlist читает объявления и составляет сообщения от вашего имени, а не от нашего, поэтому ваше резюме и переписка никогда не попадают на наши серверы. Приложение подскажет, как добавить ключ, во время настройки.",
    "not_installed": "Ещё не установили приложение? Всё необходимое здесь:",
    "reply_note": "Если что-то не работает, ответьте на это письмо — его читает живой человек.",
    "footer": "Dawnlist — продукт компании Spencer Fields Software."
  },
  "tr": {
    "subject": "Dawnlist lisans anahtarınız",
    "preheader": "Uygulamanın kilidini açmak için bunu Ayarlar'a yapıştırın.",
    "heading": "Dawnlist lisans anahtarınız",
    "thanks": "Abone olduğunuz için teşekkürler. İşte uygulamanın kilidini açan anahtar.",
    "to_use_heading": "Kullanmak için",
    "to_use_body": "Dawnlist'i açın, Ayarlar'a gidin ve anahtarı lisans alanına yapıştırın. Sahip olduğunuz her bilgisayarda, hem Windows hem de macOS sürümlerinde çalışır.",
    "allowance": "Planınız günde {count} ilana kadar kullanım sağlar.",
    "own_key": "Ayrıca kendi Anthropic API anahtarınıza ihtiyacınız olacak — Dawnlist ilanları okurken ve mesaj taslakları hazırlarken bizim hesabımızı değil sizin hesabınızı kullanır, böylece özgeçmişiniz ve yazışmalarınız sunucularımıza hiç ulaşmaz. Uygulama, kurulum sırasında bunu eklemenizde size yol gösterir.",
    "not_installed": "Henüz kurmadınız mı? Her şey şurada:",
    "reply_note": "Bir şey çalışmazsa bu mesaja yanıt verin — bir kişiye ulaşır.",
    "footer": "Dawnlist — bir Spencer Fields Software ürünüdür."
  },
  "ur": {
    "subject": "آپ کی Dawnlist لائسنس کلید",
    "preheader": "اسے ترتیبات میں پیسٹ کریں تاکہ ایپلیکیشن ان لاک ہو جائے۔",
    "heading": "آپ کی Dawnlist لائسنس کلید",
    "thanks": "سبسکرائب کرنے کا شکریہ۔ یہ رہی وہ کلید جو ایپلیکیشن کو ان لاک کرتی ہے۔",
    "to_use_heading": "استعمال کا طریقہ",
    "to_use_body": "Dawnlist کھولیں، ترتیبات میں جائیں، اور کلید کو لائسنس فیلڈ میں پیسٹ کریں۔ یہ آپ کے ہر کمپیوٹر پر کام کرتی ہے، اور Windows اور macOS دونوں ایڈیشنز پر بھی۔",
    "allowance": "آپ کا پلان روزانہ {count} تک اسامیوں کا احاطہ کرتا ہے۔",
    "own_key": "آپ کو اپنی طرف سے Anthropic کی ایک API کلید بھی درکار ہوگی — Dawnlist اسامیاں آپ کے اپنے اکاؤنٹ پر پڑھتا ہے اور پیغامات بھی وہیں تیار کرتا ہے، ہمارے اکاؤنٹ پر نہیں، اس لیے آپ کا سی وی اور آپ کی خط و کتابت کبھی بھی ہمارے سرورز تک نہیں پہنچتی۔ ایپلیکیشن سیٹ اپ کے دوران اسے شامل کرنے میں آپ کی رہنمائی کرتی ہے۔",
    "not_installed": "ابھی تک انسٹال نہیں کیا؟ سب کچھ یہاں موجود ہے:",
    "reply_note": "اگر کچھ کام نہ کرے تو اس پیغام کا جواب دیں — یہ ایک شخص تک پہنچتا ہے۔",
    "footer": "Dawnlist — Spencer Fields Software کی ایک پروڈکٹ۔"
  },
  "vi": {
    "subject": "Mã bản quyền Dawnlist của bạn",
    "preheader": "Dán mã này vào Cài đặt để mở khóa ứng dụng.",
    "heading": "Mã bản quyền Dawnlist của bạn",
    "thanks": "Cảm ơn bạn đã đăng ký. Đây là mã kích hoạt ứng dụng.",
    "to_use_heading": "Cách sử dụng",
    "to_use_body": "Mở Dawnlist, vào Cài đặt, rồi dán mã vào ô mã bản quyền. Mã này dùng được trên mọi máy tính của bạn, cả trên phiên bản Windows và macOS.",
    "allowance": "Gói của bạn cho phép tối đa {count} tin tuyển dụng mỗi ngày.",
    "own_key": "Bạn cũng sẽ cần khóa API Anthropic của riêng mình — Dawnlist đọc tin tuyển dụng và soạn thư trên tài khoản của bạn chứ không phải của chúng tôi, vì vậy CV và thư từ của bạn không bao giờ đến máy chủ của chúng tôi. Ứng dụng sẽ hướng dẫn bạn thêm khóa này trong quá trình thiết lập.",
    "not_installed": "Chưa cài đặt ứng dụng? Bạn có thể tải tại",
    "reply_note": "Nếu có gì không hoạt động, hãy trả lời email này — sẽ có người đọc và phản hồi.",
    "footer": "Dawnlist — một sản phẩm của Spencer Fields Software."
  },
  "zh": {
    "subject": "您的 Dawnlist 许可证密钥",
    "preheader": "将其粘贴到“设置”中以解锁应用程序。",
    "heading": "您的 Dawnlist 许可证密钥",
    "thanks": "感谢您的订阅。这是解锁应用程序的密钥。",
    "to_use_heading": "使用方法",
    "to_use_body": "打开 Dawnlist，进入“设置”，将密钥粘贴到许可证字段中即可。它适用于您拥有的每一台电脑，Windows 和 macOS 版本均可使用。",
    "allowance": "您的套餐每天最多支持 {count} 条招聘信息。",
    "own_key": "您还需要一个属于您自己的 Anthropic API 密钥——Dawnlist 会在您自己的账户下读取招聘信息并起草消息，而不是在我们的账户下，因此您的简历和往来信件都不会经过我们的服务器。应用程序会在设置过程中引导您添加它。",
    "not_installed": "还没有安装吗？一切都在",
    "reply_note": "如果遇到任何问题，请直接回复此邮件——会有专人查看。",
    "footer": "Dawnlist — Spencer Fields Software 出品。"
  }
};

/** Scripts written right to left. The shell sets `dir` from this. */
export const RTL = new Set(["ar", "fa", "he", "ur"]);

export function strings(lang) {
  return EMAIL_STRINGS[lang] || EMAIL_STRINGS.en;
}
